name: Database CI/CD

on:
  push:
    paths:
      - 'docker/db/**'
  workflow_dispatch:

jobs:
  docker-push-db:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (Database)
        uses: docker/build-push-action@v5
        with:
          context: ./docker/db
          file: ./docker/db/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eventup-db:latest
